# Generated by Django 6.0.4 on 2026-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iniciativa",
            name="dependencias",
            field=models.ManyToManyField(
                blank=True, related_name="desbloqueia_iniciativas", to="core.iniciativa"
            ),
        ),
    ]
