# Generated by Django 6.0.4 on 2026-04-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_iniciativa_dependencias"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAlteracao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entidade_tipo", models.CharField(choices=[("objetivo", "Objetivo"), ("iniciativa", "Iniciativa"), ("tarefa", "Tarefa"), ("plano_acao", "Plano de acao")], max_length=20)),
                ("entidade_id", models.PositiveIntegerField()),
                ("entidade_nome", models.CharField(max_length=255)),
                ("campo", models.CharField(max_length=120)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_novo", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historicos_alteracao", to="core.empresa")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historicos_alteracao", to="core.usuario")),
            ],
            options={
                "verbose_name": "Historico de alteracao",
                "verbose_name_plural": "Historicos de alteracao",
                "ordering": ["-criado_em"],
            },
        ),
    ]
