# Generated by Django 6.0.4 on 2026-04-20 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_historicoalteracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("data_hora", models.DateTimeField(default=django.utils.timezone.now)),
                ("local", models.CharField(blank=True, max_length=180)),
                ("participantes", models.TextField(blank=True)),
                ("pauta", models.TextField(blank=True)),
                ("ata", models.TextField(blank=True)),
                ("decisoes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("em_andamento", "Em andamento"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="planejada",
                        max_length=20,
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "criada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunioes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reunioes",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reuniao",
                "verbose_name_plural": "Reunioes",
                "ordering": ["-data_hora", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="EncaminhamentoReuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("detalhes", models.TextField(blank=True)),
                ("prazo", models.DateField(blank=True, null=True)),
                (
                    "tipo_geracao",
                    models.CharField(
                        choices=[("iniciativa", "Iniciativa"), ("tarefa", "Tarefa")],
                        default="tarefa",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "iniciativa_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaminhamentos_reuniao",
                        to="core.iniciativa",
                    ),
                ),
                (
                    "iniciativa_gerada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaminhamentos_origem_reuniao",
                        to="core.iniciativa",
                    ),
                ),
                (
                    "objetivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaminhamentos_reuniao",
                        to="core.objetivoestrategico",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaminhamentos_reuniao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarefa_gerada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaminhamentos_origem_reuniao",
                        to="core.tarefa",
                    ),
                ),
                (
                    "reuniao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos",
                        to="core.reuniao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaminhamento de reuniao",
                "verbose_name_plural": "Encaminhamentos de reuniao",
                "ordering": ["prazo", "descricao"],
            },
        ),
    ]
