# Generated by Django 6.0.4 on 2026-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_reuniao_encaminhamentoreuniao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicoalteracao",
            name="entidade_tipo",
            field=models.CharField(
                choices=[
                    ("objetivo", "Objetivo"),
                    ("iniciativa", "Iniciativa"),
                    ("tarefa", "Tarefa"),
                    ("plano_acao", "Plano de acao"),
                    ("reuniao", "Reuniao"),
                ],
                max_length=20,
            ),
        ),
    ]
