# Generated by Django 6.0.4 on 2026-04-20 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_historicoalteracao_entidade_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reuniao",
            name="participantes_externos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reuniao",
            name="participantes_usuarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="reunioes_participante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
