# Generated by Django 6.0.4 on 2026-04-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_reuniao_participantes_externos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReuniaoParticipanteExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=180)),
                ("email", models.EmailField(max_length=254)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "reuniao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes_externos_lista",
                        to="core.reuniao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante externo de reuniao",
                "verbose_name_plural": "Participantes externos de reuniao",
                "ordering": ["nome"],
            },
        ),
    ]
