from django.urls import path

from .views import (
    DashboardView,
    ObjectiveDetailView,
    IniciativaCreateView,
    IniciativaUpdateView,
    InitiativeDetailView,
    InitiativeListView,
    ObjetivoCreateView,
    ObjetivoUpdateView,
    ObjectiveListView,
    PlanoAcaoCreateView,
    PlanoAcaoUpdateView,
    EncaminhamentoReuniaoCreateView,
    GerarItemEncaminhamentoView,
    ReuniaoCreateView,
    ReuniaoDetailView,
    ReuniaoListView,
    ReuniaoUpdateView,
    TaskListView,
    TarefaCreateView,
    TarefaDetailView,
    TarefaUpdateView,
)

app_name = "core"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("objetivos/", ObjectiveListView.as_view(), name="objective_list"),
    path("objetivos/novo/", ObjetivoCreateView.as_view(), name="objetivo_create"),
    path("objetivos/<int:pk>/editar/", ObjetivoUpdateView.as_view(), name="objetivo_update"),
    path("objetivos/<int:pk>/", ObjectiveDetailView.as_view(), name="objective_detail"),
    path("iniciativas/", InitiativeListView.as_view(), name="initiative_list"),
    path("iniciativas/nova/", IniciativaCreateView.as_view(), name="iniciativa_create"),
    path("iniciativas/<int:pk>/editar/", IniciativaUpdateView.as_view(), name="iniciativa_update"),
    path("iniciativas/<int:pk>/", InitiativeDetailView.as_view(), name="initiative_detail"),
    path("tarefas/", TaskListView.as_view(), name="task_list"),
    path("tarefas/nova/", TarefaCreateView.as_view(), name="tarefa_create"),
    path("tarefas/<int:pk>/editar/", TarefaUpdateView.as_view(), name="tarefa_update"),
    path("planos-acao/novo/", PlanoAcaoCreateView.as_view(), name="plano_acao_create"),
    path("planos-acao/<int:pk>/editar/", PlanoAcaoUpdateView.as_view(), name="plano_acao_update"),
    path("tarefas/<int:tarefa_pk>/planos-acao/novo/", PlanoAcaoCreateView.as_view(), name="plano_acao_create_for_task"),
    path("tarefas/<int:pk>/", TarefaDetailView.as_view(), name="tarefa_detail"),
    path("reunioes/", ReuniaoListView.as_view(), name="reuniao_list"),
    path("reunioes/nova/", ReuniaoCreateView.as_view(), name="reuniao_create"),
    path("reunioes/<int:pk>/", ReuniaoDetailView.as_view(), name="reuniao_detail"),
    path("reunioes/<int:pk>/editar/", ReuniaoUpdateView.as_view(), name="reuniao_update"),
    path("reunioes/<int:reuniao_pk>/encaminhamentos/novo/", EncaminhamentoReuniaoCreateView.as_view(), name="encaminhamento_reuniao_create"),
    path("encaminhamentos/<int:pk>/gerar/", GerarItemEncaminhamentoView.as_view(), name="encaminhamento_gerar_item"),
]
